VERILOG = ../src/top.v ../src/pio.v ../src/machine.v \
          ../src/pc.v ../src/decoder.v ../src/divider.v \
	  ../src/isr.v ../src/osr.v ../src/scratch.v ../src/fifo.v

PIN_DEF = ulx3s_v20.lpf

include ulx3s.mk

