VERILOG = ../src/top.v ../src/pio.v ../src/machine.v \
          ../src/pc.v ../src/decoder.v ../src/divider.v \
          ../src/shifter.v ../src/scratch.v ../src/fifo.v

PCF_FILE = pio.pcf

include blackicemx.mk

